### ISSUE TITLE
AMP contact

### ISSUE THREAD

**Issue by fabriziogiordano** [jridgewell/PerchPages#1]
Hi Justin,
I apologize for this orthodox method of contacting you.

I am Product Manager Mobile for StreetEasy and I am evangelizing to support AMP for our listing.

Since you are Google NYC would you mind to stop by and do a
presentation of AMP to us?

Thank you,
Fabrizio

**Comment by jridgewell** [comment]
I'm asking permission internally. Can you email me at jridgewell@google?
